import jsPDF from "jspdf";

export function generateSafariPDF(booking) {
  const doc = new jsPDF();

  // ================= HEADER =================
  doc.setFont("helvetica", "bold");
  doc.setFontSize(18);
  doc.text("Luxury African Safari Itinerary", 20, 20);

  doc.setFontSize(11);
  doc.setFont("helvetica", "normal");
  doc.text("Bwera Tours & Safaris", 20, 30);

  doc.setLineWidth(0.5);
  doc.line(20, 35, 190, 35);

  // ================= CUSTOMER INFO =================
  doc.setFontSize(12);
  doc.text("Traveler Details", 20, 50);

  doc.setFontSize(10);
  doc.text(`Name: ${booking.name}`, 20, 60);
  doc.text(`Email: ${booking.email}`, 20, 68);
  doc.text(`Phone: ${booking.phone}`, 20, 76);
  doc.text(`Country: ${booking.country}`, 20, 84);

  // ================= SAFARI INFO =================
  doc.setFontSize(12);
  doc.text("Safari Details", 20, 100);

  doc.setFontSize(10);
  doc.text(`Tour: ${booking.tour}`, 20, 110);
  doc.text(`Travel Date: ${booking.date}`, 20, 118);
  doc.text(`Travelers: ${booking.people}`, 20, 126);
  doc.text(`Travel Style: ${booking.travelStyle}`, 20, 134);
  doc.text(`Budget: ${booking.budget}`, 20, 142);

  // ================= NOTES =================
  doc.setFontSize(12);
  doc.text("Special Requests", 20, 160);

  doc.setFontSize(10);

  const splitMessage = doc.splitTextToSize(
    booking.message || "No special requests provided.",
    170
  );

  doc.text(splitMessage, 20, 170);

  // ================= FOOTER =================
  doc.setFontSize(10);
  doc.setTextColor(100);
  doc.text(
    "This itinerary was generated by Bwera Tours Luxury Safari System",
    20,
    280
  );

  return doc;
}